#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-Strict
Version  : 0.47
Release  : 12
URL      : https://cpan.metacpan.org/authors/id/M/MA/MANWAR/Test-Strict-0.47.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MA/MANWAR/Test-Strict-0.47.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtest-strict-perl/libtest-strict-perl_0.45-1.debian.tar.xz
Summary  : 'Check syntax, presence of use strict; and test coverage'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-Strict-license = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(IO::Scalar)

%description
testing strictness in a distribution, by Pierre Denis <pdenis@gmail.com>.
* Installation

%package dev
Summary: dev components for the perl-Test-Strict package.
Group: Development
Provides: perl-Test-Strict-devel = %{version}-%{release}

%description dev
dev components for the perl-Test-Strict package.


%package license
Summary: license components for the perl-Test-Strict package.
Group: Default

%description license
license components for the perl-Test-Strict package.


%prep
%setup -q -n Test-Strict-0.47
cd ..
%setup -q -T -D -n Test-Strict-0.47 -b 1
mkdir -p deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Test-Strict-0.47/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-Strict
cp LICENSE %{buildroot}/usr/share/package-licenses/perl-Test-Strict/LICENSE
cp deblicense/copyright %{buildroot}/usr/share/package-licenses/perl-Test-Strict/deblicense_copyright
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/Test/Strict.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::Strict.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Test-Strict/LICENSE
/usr/share/package-licenses/perl-Test-Strict/deblicense_copyright
